# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
require 'open-uri'

# case Rails.env
#     when "development"
#         ADD YOUR TESTING VIDEOS
#     when "production"
#         ADD ALL YOUR VIDEOS
# end

User.destroy_all
Movie.destroy_all

User.create({username: "demouser", password: "demouserpassword", email: "demouser@demouser.com", autoplay: true})
User.create({username: "sethb", password: "password", email: "sethbarrie@gmail.com", autoplay: false})
User.create({username: "tiam1029", password: "password", email: "tiam1029", autoplay: false})
User.create({username: "a-rod", password: "doomaintcomingout", email: "360forlyfe@gmail.com", autoplay: false})
User.create({username: "maxi3", password: "gooftroop", email: "neverlikethefirsttime@gmail.com", autoplay: false})
User.create({username: "kirby", password: "thedog", email: "sakuraiwyhy@gmail.com", autoplay: false})
User.create({username: "thisisgibberish", password: "ifoundaway", email: "gibbyandkat@gmail.com", autoplay: false})
User.create({username: "tom", password: "andjerry", email: "boomer_aang@gmail.com", autoplay: false})
User.create({username: "whyyou", password: "gotta", email: "momsspaggethi@gmail.com", autoplay: false})
User.create({username: "doyoueverfeel", password: "likeaplasticbag", email: "driftingthroughthewind@wantingtostartagain.com", autoplay: false})
User.create({username: "hopeigethired", password: "likereallysoon", email: "ohplzgeezus@gmail.com", autoplay: false})




titles = [
    "The Stray",
    "Beverly Hills Chihuahua",
    '101 Dalmatians',
    'All Dogs Go to Heaven',
    'Lady and the Tramp',
    'Air Bud',
    'Hotel for Dogs',
    "A Dog's Journey",
    "Scooby-Doo! and the Witch's Ghost",
    "Oliver & Company",
    'Turner & Hooch',
    "Clifford's Really Big Movie",
    "Homeward Bound: The Incredible Journey",
    "Balto",
    'Cats & Dogs',
    'Because of Winn-Dixie',
    'Far from Home: The Adventures of Yellow Dog',
    "A Dog's Way Home",
    'Benji',
    'The Secret Life of Pets',
    'Marley & Me',
    'Dog Days',
    'The Shaggy Dog',
    'The Fox and the Hound',
    'Eight Below',
    'My Dog Skip',
    'Wiener-Dog',
    'The Adventures of Milo and Otis',
    'Red Dog',
    'As Good As It Gets',
    'Oddball',
    'Lassie',
    'Bolt',
    'Snoopy Come Home',
    'Beethoven',
    'Show Dogs',
    'Snow Dogs',
    'The Secret Life of Pets 2',
    'Air Buddies',
    "Beethoven's 2nd",
    'Cats & Dogs: The Revenge of Kitty Galore',
    'Chilly Christmas',
    'Cybermutt',
    'The Dog Who Saved Christmas Vacation',
    'Doctor Dolittle',
    'Firehouse Dog',
    'Hearty Paws 2',
    'Jock the Hero Dog',
    'The Karate Dog',
    'Life Is Ruff',
    'Marley & Me: The Puppy Years',
    'Marmaduke'
]

directors = [
    'Mitch Davis',
    'Raja Gosnell',
    'Stephen Herek',
    'Don Bluth & Gary Goldman',
    'Wilfred Jackson & Hamilton Luske',
    'Charles Martin Smith',
    'Thor Freudenthal',
    'Gail Mancuso',
    'Jim Stenstrum',
    'George Scribner',
    'Roger Spottiswoode',
    'Robert C. Ramirez',
    'Duwayne Dunham',
    'Simon Wells',
    'Lawrence Guterman',
    'Wayne Wang',
    'Phillip Borsos',
    'Charles Martin Smith',
    'Brandon Camp',
    'Chris Renaud',
    'David Frankel',
    'Ken Marino',
    'Brian Robbins',
    'Richard Rich & Art Stevens',
    'Frank Marshall',
    'Jay Russell',
    'Todd Solondz',
    'Masanori Hata',
    'Kriv Stenders',
    'James L. Brooks',
    'Stuart McDonald',
    'Daniel Petrie',
    'Byron Howard & Chris Williams',
    'Bill Melendez',
    'Brian Levant',
    'Raja Gosnell',
    'Brian Levant',
    'Chris Renaud',
    'Robert Vince',
    'Rod Daniel',
    'Brad Peyton',
    'Gregory Poppen',
    'George T. Miller',
    'Michael Feifer',
    'Richard Fleischer',
    'Todd Holland',
    'Jeong-cheol Lee',
    'Duncan MacNeillie',
    'Bob Clark',
    'Charles Haid',
    'Michael Damian',
    'Tom Dey'
]

years = [
    2017,
    2008,
    1996,
    1989,
    1955,
    1997,
    2009,
    2019,
    1999,
    1988,
    1989,
    2004,
    1993,
    1995,
    2001,
    2005,
    1995,
    2019,
    2018,
    2016,
    2008,
    2018,
    2006,
    1981,
    2006,
    2000,
    2016,
    1986,
    2011,
    1997,
    2015,
    1994,
    2008,
    1972,
    1992,
    2018,
    2002,
    2019,
    2006,
    1993,
    2010,
    2012,
    2003,
    2010,
    1967,
    2007,
    2010,
    2011,
    2004,
    2005,
    2011,
    2010
]


rating = [
    'pg',
    'pg',
    'g',
    'g',
    'g',
    'pg',
    'pg',
    'pg',
    'not rated',
    'g',
    'pg',
    'g',
    'g',
    'g',
    'pg',
    'pg',
    'pg',
    'pg',
    'not rated',
    'pg',
    'pg',
    'pg',
    'pg',
    'g',
    'pg',
    'pg',
    'r',
    'g',
    'pg',
    'pg-13',
    'g',
    'pg',
    'pg',
    'g',
    'g',
    'pg',
    'pg',
    'pg',
    'pg',
    'pg',
    'pg',
    'g',
    'pg',
    'pg',
    'g',
    'pg',
    'not rated',
    'pg',
    'pg',
    'g',
    'pg',
    'pg'
]

description = [
    "Young Christian Davis finds a stray dog named Pluto and decides to bring it home to his parents and two siblings. Christian's father, Mitch, works long hours and his mother Michelle just wants a husband who's there for the family. But in just a short time with the Davis clan, Pluto manages to rescue a lost toddler, bring comfort to Christian and help save Mitch and Michelle's struggling marriage.",
    'Beverly Hills Chihuahua is a Mexican-American film trilogy. The films are based on a chihuahua named "Papi" going through adventures alongside his family and friends.',
    "The dastardly Cruella De Vil chances upon a litter of cute dalmatian puppies and decides that their skins will make her the perfect new coat. After she sends two hapless heavies to steal the dogs, it is up to parents Pongo and Perdy to stage a daring rescue. Joining them for the adventure are their human `pets' and host of guest animals including a cheeky raccoon and a helpful horse.",
    'All Dogs Go to Heaven is a 1989 animated musical fantasy comedy-drama adventure film directed by Don Bluth and co-directed by Gary Goldman (his directorial debut) and Dan Kuenster. It tells the story of Charlie B.',
    "This Disney animated classic follows a pampered cocker spaniel named Lady (Barbara Luddy) whose comfortable life slips away once her owners have a baby. When, after some tense circumstances, Lady finds herself on the loose and out on the street, she is befriended and protected by the tough stray mutt Tramp (Larry Roberts). A romance begins to blossom between the two dogs, but their many differences, along with more drama at Lady's household, threaten to keep them apart.",
    "Diffident in the wake of his father's death, high schooler Josh (Kevin Zegers) struggles to adapt to his new home in Washington state. That all changes, however, when he signs up to be the school basketball team's manager and discovers that his pet dog Bud, a stray golden retriever he took in, can play the sport amazingly well. After Bud joins the team, Josh's life brightens considerably, until the dog's former owner Norm Snively (Michael Jeter) returns in hopes of reclaiming the pooch.",
    "After moving into a foster home that forbids pets, siblings Andi (Emma Roberts) and Bruce (Jake T. Austin) must quickly find a home for their dog, Friday. The resourceful pair find an abandoned hotel, and with the help of Bruce's mechanical skills, turn it into a pooch paradise for Friday and a number of strays. But when the inevitable barking makes neighbors suspicious, Andi and Bruce must find a way to hide their canine haven from prying eyes.",
    "Bailey is living the good life on the Michigan farm of his boy, Ethan and Ethan's wife Hannah. He even has a new playmate: Ethan and Hannah's baby granddaughter, CJ. The problem is that CJ's mom, Gloria, decides to take CJ away. As Bailey's soul prepares to leave this life for a new one, he makes a promise to Ethan to find CJ and protect her at any cost. Thus begins Bailey's adventure through many lives filled with love, friendship, and devotion.",
    "The gang meet a horror writer who invites them to go back to his hometown for the Autumn Fest, where they learn that one of the writers ancestors was a witch who is apparently haunting the city.",
    'In this animated update of the classic "Oliver Twist" tale, Oliver (Joey Lawrence) is an orphaned kitten taken in by a gang of thieving dogs, led by cavalier canine Dodger (Billy Joel) and owned by down-and-out pickpocket Fagin (Dom DeLuise). While pulling a job in the streets of New York City, Oliver winds up being adopted by a rich girl, Jenny (Natalie Gregory), and landing on easy street. But through a series of events, a loan shark threatens the peaceful new arrangement.',
    "Det. Scott Turner (Tom Hanks) is an uptight, by-the-book police officer who hopes to leave his sleepy California town and work in the big city. When his friend Amos Reed (John McIntire), the proprietor of a junkyard, is killed, Turner reluctantly inherits the man's dog. Realizing that the canine may be able to help him solve the murder case, Turner attempts to adjust to life with the big dog, resulting in much household destruction and unwelcome chaos.",
    "Worried that his owners are spending too much on his food, Clifford the dog runs away to the circus with the intention of winning a lifetime supply of Tummy Yummies.",
    "Three pets are left behind while their owners go on a holiday. Thinking they have been abandoned, the pets embark on a journey to California to be reunited with them.",
    "In this animated feature, a deadly diphtheria epidemic strikes the remote town of Nome, Alaska. With the life-saving medicine located hundreds of miles away, the residents decide to send out a sled-dog team. Balto (Kevin Bacon) -- a half-wolf dog ignored by all except a goose, Boris (Bob Hoskins), and two polar bears -- is chosen to run but is disqualified by lead dog Steele (Jim Cummings). When the other dogs get lost in the snow, Balto risks his life to rescue them and deliver the medicine.",
    "'Cats & Dogs' uncovers the truth about the high-tech, secret war being waged in neighborhoods everywhere that humans aren't even aware of: an eternal struggle between the two great armies of Cats and Dogs. The story follows a Cat plan to destroy a new vaccine that, if developed, would destroy all human allergies to Dogs, and the Dogs' efforts to stop the Cats from executing their plan.",
    "Abandoned by her mother years ago, Opal (AnnaSophia Robb), a 10-year-old girl, moves with her preacher father (Jeff Daniels) to a small town in Florida. Lonely and missing her old friends, Opal is ecstatic to find companionship with a rambunctious little dog she names Winn-Dixie, after the store where she found the pup. With Winn-Dixie's help, Opal befriends several colorful townsfolk (Cicely Tyson, Eva Marie Saint, Dave Matthews) and even begins mending her relationship with her father.",
    "While sailing off the shore of British Columbia, John McCormick (Bruce Davison), his son, Angus (Jesse Bradford), and the boy's Labrador retriever, Yellow, encounter severe weather. When Angus and Jesse are knocked overboard, John struggles to rescue them, but to no avail. After washing up on the coast of a remote wilderness region, Angus and his dog do their best to survive, contending with both the elements and dangerous wildlife as the boy's parents embark on a quest to find them.",
    'As a puppy, Bella finds her way into the arms of Lucas, a young man who gives her a good home. When Bella becomes separated from Lucas, she soon finds herself on an epic 400-mile journey to reunite with her beloved owner. Along the way, the lost but spirited dog touches the lives of an orphaned mountain lion, a down-on-his-luck veteran and some friendly strangers who happen to cross her path.',
    'A dog comes to the rescue and helps heal a broken family when a boy and his sister stumble into serious danger.',
    "Max (Redacted) is a spoiled terrier who enjoys a comfortable life in a New York building until his owner adopts Duke, a giant and unruly canine. During their walk outside, they encounter a group of ferocious alley cats and wind up in a truck that's bound for the pound. Luckily, a rebellious bunny named Snowball swoops in to save the doggy duo from captivity. In exchange, Snowball demands that Max and Duke join his gang of abandoned pets on a mission against the humans who've done them wrong.",
    "Newlyweds John and Jenny Grogan (Owen Wilson, Jennifer Aniston) leave behind snowy Michigan and move to Florida, where they buy their first home and find jobs at competing newspapers. Soon afterward, the Grogans adopt Marley, an adorable yellow Labrador pup. But Marley soon grows up to be a mischievous handful. Still, even while he's destroying the furniture and failing obedience school, he always manages to bring out the best in John, Jenny and their growing family.",
    "Elizabeth is a charming anchorwoman who seeks advice from her dog's therapist. Tara is a spunky barista who dreams of a life beyond the coffee shop. Daisy is a dog walker who's enamoured with a client. Garrett pines for a woman while trying to keep his adopt-a-dog business afloat. The beloved canines in their lives soon start to influence their careers, friendships and romantic relationships in funny and unexpected ways.",
    'Deputy District Attorney Dave Douglas (Tim Allen) is a workaholic and frequently puts his job before his family. After taking on a case involving an animal laboratory, he becomes infected with a top-secret serum that transforms him into a dog. Life as a canine gives Dave new perspective on the importance of family, but before he can make things right with his wife and kids, he must sniff out the villains responsible for the serum.',
    'A little fox named Tod, and Copper, a hound puppy, vow to be best buddies forever. But as Copper grows into a hunting dog, their unlikely friendship faces the ultimate test.',
    'The frozen wasteland of Antarctica serves as the background for a tale about the bonds of friendship and loyalty. Three members of a scientific expedition, Jerry Shepard (Paul Walker), his friend Cooper (Jason Biggs) and an American geologist (Bruce Greenwood), must leave their beloved sled dogs behind after a devastating accident and increasingly perilous weather conditions. Alone, the dogs struggle to survive the harsh Antarctic winter.',
    "Who says best friends have to be human? Not Willie Morris (Frankie Muniz), who receives a talented terrier named Skip for his birthday. With Skip's remarkable and unconventional help, Willie and Skip turn bullies into friends, tangle with hapless moonshiners, and even win the affections of the prettiest girl in school.",
    'A cute dachshund puppy impacts an assortment of dysfunctional people as it finds itself shuffled from one oddball owner to the next, including two couples, a veterinary nurse, a screenwriter and a bitter woman.',
    'The adventures of a young cat and a dog as they find themselves accidentally straying from their farm in Japan.',
    'An Australian dog manages to unite a fractured community during its epic quest to find its beloved human.',
    "Melvin Udall (Jack Nicholson) is an obsessive-compulsive writer of romantic fiction who's rude to everyone he meets, including his gay neighbor Simon (Greg Kinnear), but when he has to look after Simon's dog, he begins to soften and, if still not completely over his problems, finds he can conduct a relationship with the only waitress (Helen Hunt) at the local diner who'll serve him.",
    'An eccentric chicken farmer, with the help of his granddaughter, trains his mischievous dog Oddball to protect a penguin sanctuary from fox attacks in an attempt to reunite his family and save their seaside town.',
    "On their way to start a new life at a sheep farm in rural Virginia, the Turner family are halted by a wreck on the highway that has claimed the life of a truck driver. Spotting the trucker's now-abandoned collie on the side of the road, they take pity on the dog and adopt her. As the city family copes with the change to rural life, including a feud with a neighboring farm family who resent the city interlopers, the ever-loyal Lassie helps them adjust to their new surroundings.",
    "The days of canine superstar Bolt (John Travolta) are filled with danger and intrigue ... until the cameras stop rolling. But Bolt doesn't know that he's on a TV show; he thinks his amazing powers are real. When Bolt is accidentally shipped from his Hollywood soundstage to the mean streets of New York, he begins his most-amazing adventure: Armed only with his delusions and accompanied by a cat and a hamster, he sets out to to find his owner, Penny (Miley Cyrus).",
    "Charlie Brown's (Chad Webber) beloved dog Snoopy (Bill Melendez) receives a letter from his original owner, Lila (Johanna Baer), who has been sick in the hospital. With his bird friend Woodstock, Snoopy goes to visit Lila, making his way across the country despite seeing 'no dogs allowed' signs everywhere. When Lila gets better, she asks Snoopy to live with her. After a farewell party, he sets out to live with Lila, leaving Charlie Brown depressed.",
    'A slobbering St. Bernard becomes the center of attention for a loving family, but must contend with a dog-napping veterinarian and his henchmen.',
    "After a failed attempt to recover a stolen baby panda, police dog Max reluctantly teams up with a human FBI agent named Frank. A hot tip leads Max and Frank to Las Vegas for the world's most exclusive dog show. To find the panda, Max goes under cover as a contestant to get the lowdown from his fellow canines. With help from their new friends, the crime-fighting duo must now foil another kidnapping plot and rescue other valuable animals from a gang of greedy smugglers.",
    "When Miami dentist Ted Brooks (Cuba Gooding Jr.) finds out that he's been named in a will, he travels to Alaska to claim his inheritance. Once he gets there, however, his dreams turn to mush: he discovers he's been left a mischievous team of sled dogs -- who have got it in for him. Making matters even worse is the crusty mountain man Thunder Jack (James Coburn), who's also got it in for the city slicker. Wanting to claim the dogs for himself, Jack urges Ted to hotfoot it back to warmer climates.",
    "Max the terrier encounters canine-intolerant cows, hostile foxes and a scary turkey when he visits the countryside. Luckily for Max, he soon catches a break when he meets Rooster, a gruff farm dog who tries to cure the lovable pooch of his neuroses.",
    'Five talking puppies band together to save their kidnapped mother and father from an evil exotic dog hunter.',
    "The Newtons, helmed by George (Charles Grodin) and Alice (Bonnie Hunt), are in for another St. Bernard adventure when their dog, Beethoven, falls in love with fellow canine Missy and makes a family of his own. But instead of being one big happy family, Missy's owner, Regina (Debi Mazar), wants to sell off the puppies to make a huge profit. Springing into action, the Newton kids rescue the little dogs before Regina can make her deal -- but she is determined to get them back.",
    "In the age-old battle between felines and canines, one rogue kitty is stepping up the fight. Kitty Galore, former operative for MEOWS, is executing a diabolical plan against her sworn enemies, the dogs, as well as her cat comrades. In order to save themselves and their humans, both species must unite in an unprecedented alliance to stop Kitty Galore from making the world her scratching post.",
    "Bobby trains his dog Chilly to be a city dog after his father gets a job in New York City. His father is not convinced Chilly should go until a dog thief (Tom Arnold) breaks into their home and Chilly uses his training to protect their home.",
    "A scientist (Judd Nelson) uses a computer chip to transform the dog that saved his life into a bionic canine.",
    "The Bannister family - including former K-9 police hero Zeus (voiced by Mario López) - is back, and this time they're spending their holidays at a beautiful Rocky Mountain resort.",
    "Dr. John Dolittle (Rex Harrison) lives in a small English village where he specializes in caring for and verbally communicating with animals. When Dr. Dolittle is unjustly sent to an insane asylum for freeing a lovesick seal from captivity, his animals and two closest human friends, Matthew Mugg (Anthony Newley) and Tommy Stubbins (William Dix), liberate him. Afterward, they join Emma Fairfax (Samantha Eggar) and set out by boat to find a famed and elusive creature: the Great Pink Sea Snail.",
    "When a commercial shoot goes terribly wrong, Rex, Hollywood's biggest canine star, goes missing and is presumed dead by his handlers. Rex takes refuge in a row of lofts, but the structure catches fire, and Rex makes a death-defying leap into a fire captain's (Bruce Greenwood) arms. The man's son, Shane (Josh Hutcherson), becomes Rex's reluctant new master, and the firefighters adopt the dog as their mascot. Trouble looms when Rex's handlers try to get him back.",
    "Lovable Labrador Maeumee tracks thieves after they take her smallest puppy.",
    "A man and his best friend, a small lovable dog find adventure in 1880s Africa.",
    "A talking canine (Chevy Chase) that knows martial arts helps a detective (Simon Rex) to track down a criminal.",
    "Calvin is a likeable, bright 13-year-old who has almost everything he could want in life - except a prized rare copy of a comic he collects. When he hears about a dog show with a $5,000 prize, he decides to get a dog and enter, to win the money and buy the comic. However, he doesn't bargain for the fact that he comes to love Tyco, the accident prone, lovable mutt he rescues from the pound.",
    "The world's worst talking canine (Grayson Russell) wreaks havoc on a dog contest.",
    "With the help of his best feline friend, a lovable Great Dane named Marmaduke (Owen Wilson) helps his family (Lee Pace, Judy Greer) adjust to their new lives in Orange County, California. Although he is loving life and living large in The O.C., he is discovering that fitting in with his new pals at the dog park is not always easy."
    ]

clips = [
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/video/clip000.mp4',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/video/clip001.mp4',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/video/clip002.mp4',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/video/clip003.mp4',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/video/clip004.mp4',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/video/clip005.mp4',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/video/clip006.mp4',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/video/clip007.mp4',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/video/clip008.mp4',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/video/clip009.mp4',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/video/clip010.mp4',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/video/clip011.mp4',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/video/clip012.mp4',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/video/clip013.mp4',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/video/clip014.mp4',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/video/clip015.mp4',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/video/clip016.mp4',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/video/clip017.mp4',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/video/clip018.mp4',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/video/clip019.mp4',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/video/clip020.mp4',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/video/clip021.mp4',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/video/clip022.mp4',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/video/clip023.mp4',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/video/clip024.mp4',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/video/clip025.mp4',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/video/clip026.mp4',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/video/clip027.mp4',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/video/clip028.mp4',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/video/clip029.mp4',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/video/clip030.mp4',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/video/clip031.mp4',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/video/clip032.mp4',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/video/clip033.mp4',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/video/clip034.mp4',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/video/clip035.mp4',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/video/clip036.mp4',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/video/clip037.mp4',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/video/clip038.mp4',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/video/clip039.mp4',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/video/clip040.mp4',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/video/clip041.mp4',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/video/clip042.mp4',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/video/clip043.mp4',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/video/clip044.mp4',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/video/clip045.mp4',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/video/clip046.mp4',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/video/clip047.mp4',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/video/clip048.mp4',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/video/clip049.mp4',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/video/clip050.mp4',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/video/clip051.mp4'

]
    
covers = [
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/cover-picture/cover000.jpg',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/cover-picture/cover001.jpg',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/cover-picture/cover002.jpg',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/cover-picture/cover003.jpg',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/cover-picture/cover004.jpg',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/cover-picture/cover005.jpeg',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/cover-picture/cover006.jpg',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/cover-picture/cover007.jpg',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/cover-picture/cover008.jpg',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/cover-picture/cover009.jpg',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/cover-picture/cover010.jpg',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/cover-picture/cover011.jpg',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/cover-picture/cover012.jpg',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/cover-picture/cover013.jpg',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/cover-picture/cover014.jpg',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/cover-picture/cover015.jpg',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/cover-picture/cover016.jpg',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/cover-picture/cover017.jpg',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/cover-picture/cover018.jpg',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/cover-picture/cover019.jpg',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/cover-picture/cover020.jpg',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/cover-picture/cover021.jpg',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/cover-picture/cover022.jpg',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/cover-picture/cover023.jpg',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/cover-picture/cover024.jpg',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/cover-picture/cover025.jpg',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/cover-picture/cover026.jpg',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/cover-picture/cover027.jpg',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/cover-picture/cover028.jpg',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/cover-picture/cover029.jpg',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/cover-picture/cover030.png',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/cover-picture/cover031.png',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/cover-picture/cover032.jpg',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/cover-picture/cover033.png',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/cover-picture/cover034.jpg',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/cover-picture/cover035.jpg',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/cover-picture/cover036.jpg',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/cover-picture/cover037.jpg',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/cover-picture/cover038.png',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/cover-picture/cover039.jpg',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/cover-picture/cover040.png',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/cover-picture/cover041.png',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/cover-picture/cover042.jpg',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/cover-picture/cover043.jpg',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/cover-picture/cover044.jpg',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/cover-picture/cover045.jpg',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/cover-picture/cover046.png',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/cover-picture/cover047.jpg',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/cover-picture/cover048.jpg',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/cover-picture/cover049.jpg',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/cover-picture/cover050.png',
    'https://dogflix-seed-bucket.s3-us-west-2.amazonaws.com/cover-picture/cover051.jpg'

]


yt_link = [
    'https://www.youtube.com/watch?v=8PLbC0IvKtc',
    'https://www.youtube.com/watch?v=PRKLQ-8wZuQ',
    'https://www.youtube.com/watch?v=yikjQpxs8ac',
    'https://www.youtube.com/watch?v=GUvk7NNmB64',
    'https://www.youtube.com/watch?v=oVG-vQNbiJQ',
    'https://www.youtube.com/watch?v=0cOrwS3Xihw',
    'https://www.youtube.com/watch?v=ObY7W7BVypA',
    'https://www.youtube.com/watch?v=A2FrrSyyKfA',
    'https://www.youtube.com/watch?v=3sPDwDok_qA',
    'https://www.youtube.com/watch?v=mXlLTEO-3dc',
    'https://www.youtube.com/watch?v=bqDf22JiTyw',
    'https://www.youtube.com/watch?v=eRNPQmk6wLU',
    'https://www.youtube.com/watch?v=KtpFx0JsT90',
    'https://www.youtube.com/watch?v=HJwvbmRXym4',
    'https://www.youtube.com/watch?v=CKZtif47lA4',
    'https://www.youtube.com/watch?v=ZpsE_7oLdAU',
    'https://www.youtube.com/watch?v=xomFz0FPeCQ',
    'https://www.youtube.com/watch?v=1pKdCHvH310',
    'https://www.youtube.com/watch?v=UqtFvSKhKmA',
    'https://www.youtube.com/watch?v=i-80SGWfEjM',
    'https://www.youtube.com/watch?v=VQiUxEcFnAo',
    'https://www.youtube.com/watch?v=RUuFMEnFI6Q',
    'https://www.youtube.com/watch?v=S09rcCJl8pc',
    'https://www.youtube.com/watch?v=Ae1zDwsmARI',
    'https://www.youtube.com/watch?v=zz7TGf1awDo',
    'https://www.youtube.com/watch?v=NtS1kDW8PEo',
    'https://www.youtube.com/watch?v=8C7OewoxnKI',
    'https://www.youtube.com/watch?v=Kz_LSe6_E7Y',
    'https://www.youtube.com/watch?v=GTExiWzvJlo',
    'https://www.youtube.com/watch?v=p_c-LiN9HNw',
    'https://www.youtube.com/watch?v=P7AV2ZYlxvI',
    'https://www.youtube.com/watch?v=2gPfo70aLac',
    'https://www.youtube.com/watch?v=IBsg00NnzGg',
    'https://www.youtube.com/watch?v=M7RvYrs5WRA',
    'https://www.youtube.com/watch?v=ki8wHMR-yOI',
    'https://www.youtube.com/watch?v=gHtbBsGdUgw',
    'https://www.youtube.com/watch?v=UBgBG2XTyug',
    'https://www.youtube.com/watch?v=mYocfuqu2A8',
    'https://www.youtube.com/watch?v=0okvMkIXRNc',
    'https://www.youtube.com/watch?v=ut47bPSo8pI',
    'https://www.youtube.com/watch?v=3JnxaZunOAo',
    'https://www.youtube.com/watch?v=Ty2bhW9fsyU',
    'https://www.youtube.com/watch?v=wA9mSybeang',
    'https://www.youtube.com/watch?v=lvR73IHRaWo',
    'https://www.youtube.com/watch?v=LWbtxG-jXMY',
    'https://www.youtube.com/watch?v=98kbJ-vsKuQ',
    'https://www.youtube.com/watch?v=IBnG7RBBv5U',
    'https://www.youtube.com/watch?v=zG7nIP30ioM',
    'https://www.youtube.com/watch?v=5f9BtkXgUw0',
    'https://www.youtube.com/watch?v=H4GB7dQkkfM',
    'https://www.youtube.com/watch?v=0slO2_B_k6g',
    'https://www.youtube.com/watch?v=xGx6IhjoWqw'
]

cover_filename = [
    'cover000.jpg',
    'cover001.jpg',
    'cover002.jpg',
    'cover003.jpg',
    'cover004.jpg',
    'cover005.jpeg',
    'cover006.jpg',
    'cover007.jpg',
    'cover008.jpg',
    'cover009.jpg',
    'cover010.jpg',
    'cover011.jpg',
    'cover012.jpg',
    'cover013.jpg',
    'cover014.jpg',
    'cover015.jpg',
    'cover016.jpg',
    'cover017.jpg',
    'cover018.jpg',
    'cover019.jpg',
    'cover020.jpg',
    'cover021.jpg',
    'cover022.jpg',
    'cover023.jpg',
    'cover024.jpg',
    'cover025.jpg',
    'cover026.jpg',
    'cover027.jpg',
    'cover028.jpg',
    'cover029.jpg',
    'cover030.png',
    'cover031.png',
    'cover032.jpg',
    'cover033.png',
    'cover034.jpg',
    'cover035.jpg',
    'cover036.jpg',
    'cover037.jpg',
    'cover038.png',
    'cover039.jpg',
    'cover040.png',
    'cover041.png',
    'cover042.jpg',
    'cover043.jpg',
    'cover044.jpg',
    'cover045.jpg',
    'cover046.png',
    'cover047.jpg',
    'cover048.jpg',
    'cover049.jpg',
    'cover050.png',
    'cover051.jpg'
]

movie_filename = [
    'clip000.mp4',
    'clip001.mp4',
    'clip002.mp4',
    'clip003.mp4',
    'clip004.mp4',
    'clip005.mp4',
    'clip006.mp4',
    'clip007.mp4',
    'clip008.mp4',
    'clip009.mp4',
    'clip010.mp4',
    'clip011.mp4',
    'clip012.mp4',
    'clip013.mp4',
    'clip014.mp4',
    'clip015.mp4',
    'clip016.mp4',
    'clip017.mp4',
    'clip018.mp4',
    'clip019.mp4',
    'clip020.mp4',
    'clip021.mp4',
    'clip022.mp4',
    'clip023.mp4',
    'clip024.mp4',
    'clip025.mp4',
    'clip026.mp4',
    'clip027.mp4',
    'clip028.mp4',
    'clip029.mp4',
    'clip030.mp4',
    'clip031.mp4',
    'clip032.mp4',
    'clip033.mp4',
    'clip034.mp4',
    'clip035.mp4',
    'clip036.mp4',
    'clip037.mp4',
    'clip038.mp4',
    'clip039.mp4',
    'clip040.mp4',
    'clip041.mp4',
    'clip042.mp4',
    'clip043.mp4',
    'clip044.mp4',
    'clip045.mp4',
    'clip046.mp4',
    'clip047.mp4',
    'clip048.mp4',
    'clip049.mp4',
    'clip050.mp4',
    'clip051.mp4'
]

titles.each_with_index do |movie_title, idx|
    temp_movie = Movie.create({
        title: titles[idx], 
        description: description[idx], 
        rating: rating[idx], 
        director: directors[idx],
        year: years[idx], 
        video_url: yt_link[idx]
    })
    temp_clip = open(clips[idx])
    temp_cover = open(covers[idx])
    temp_movie.movie_clip.attach(io: temp_clip, filename: movie_filename[idx])
    temp_movie.cover_art.attach(io: temp_cover, filename: cover_filename[idx])

end
