export const RANDOM_DESCRIPTOR = [

                "Absurd"
                ,"Alien"
                ,"Animal"
                ,"Art"
                ,"Biographical"
                ,"Bollywood"
                ,"Bounty-Hunter"
                ,"Buddy"
                ,"Campy"
                ,"Chilling"
                ,"Classic"
                ,"Coming-of-age"
                ,"Conspiracy"
                ,"Controversial"
                ,"Cop"
                ,"Courtroom"
                ,"Cult"
                ,"Cynical"
                ,"Dark"
                ,"Deadpan"
                ,"Deep Sea"
                ,"Detective"
                ,"Disney"
                ,"Emotional"
                ,"Epic"
                ,"Experimental"
                ,"Feel-good"
                ,"Gambling"
                ,"Gangster"
                ,"Girl Power"
                ,"Goofy"
                ,"Gory"
                ,"Gritty"
                ,"Haunted House"
                ,"Heartfelt"
                ,"Heist"
                ,"Imaginative"
                ,"Independent"
                ,"Inspiring"
                ,"Irreverent"
                ,"Kung Fu"
                ,"Mad-Scientist"
                ,"Magical"
                ,"Martial Arts"
                ,"Medical"
                ,"Mid-Life-Crisis"
                ,"Military"
                ,"Monster"
                ,"Ominous"
                ,"Political"
                ,"Prison"
                ,"Provocative"
                ,"Psychological"
                ,"Quirky"
                ,"Raunchy"
                ,"Road Trip"
                ,"Rogue-Cop"
                ,"Romantic"
                ,"Scary"
                ,"Sentimental"
                ,"Serial Killer"
                ,"Slapstick"
                ,"Social Issue"
                ,"Space-Travel"
                ,"Spy"
                ,"Steamy"
                ,"Supernatural"
                ,"Suspenseful"
                ,"Talking-Animal"
                ,"Tearjerkers"
                ,"Teen"
                ,"Time Travel"
                ,"Travel"
                ,"Treasure Hunt"
                ,"Underdog"
                ,"Understated"
                ,"Vampire"
                ,"Violent"
                ,"Viral Plague"
                ,"War"
                ,"Werewolf"
                ,"Witty"
                ,"Workplace"
                ,"Zombie"
]